# Generated by Django 5.2.1 on 2025-05-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='plain_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
