# Generated by Django 5.2.1 on 2025-06-23 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_document_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
